### ISSUE TITLE
ERROR in @creativeBulma/bulma-toolip/src/sass/index.sass

### ISSUE THREAD

**Issue by MiroDevGit** [CreativeBulma/bulma-tooltip#10]
the styles I'm importing are as follows (see image below)
![image](https://user-images.githubusercontent.com/28606299/88318571-32e68280-cd1b-11ea-944c-e6738bdffd04.png)
however when I compile my scss file I get the following error:
![image](https://user-images.githubusercontent.com/28606299/88318722-72ad6a00-cd1b-11ea-973e-65163e0a73eb.png)
first of all I'm not even importing the sass file as you can see, secondly it looks like the bulma _initial-variables aren't used?

anyway I don't really know what I'm doing wrong, so if anyone could provide some help that would be great.

**Comment by MiroDevGit** [comment]
Holy smokes, I feel incredibly stupid but somehow i managed to include the sass in my app.js
I am so sorry but it's fixed now obviously

**Comment by ulf-frostypaw** [comment]
I have the same problem, but I am not importing the sass in my app.js
