### ISSUE TITLE
Tooltip cropped inside Bulma's .table-container

### ISSUE THREAD

**Issue by ZedoGado** [CreativeBulma/bulma-tooltip#15]
When a tooltip expands above the upper limit of a div with class table-container it gets cropped due to overflow settings.
You can find an example attached.

Thank you!
Best regards

![Sem Título](https://user-images.githubusercontent.com/23087036/103479261-63e7da80-4dc4-11eb-9d99-424edac4f47d.png)

**Comment by jLynx** [comment]
I am also having this issue. It seems to be the same as https://github.com/CreativeBulma/bulma-tooltip/issues/26

**Comment by ZedoGado** [comment]
It appears this is a limitation of the various CSS properties needed and there is no pure CSS way to overcome the problem. There are JS-based solutions avaliable for positioning tooltips that are more robust and flexible. I am closing the ticket. Thank you
