### ISSUE TITLE
Issues with combination of arrow and directions options

### ISSUE THREAD

**Issue by oliverfindl** [CreativeBulma/bulma-tooltip#3]
Hello @CreativeBulma,

huge thanks for this cool package for [Bulma](https://github.com/jgthms/bulma)!

Unfortunately I'm encountering some issues when I want to use tooltip with arrow in combination with different directions for different breakpoints.

I'm using this class combination:
```css
.has-tooltip-arrow.has-tooltip-right-touch.has-tooltip-bottom-desktop.has-tooltip-fade
```

As result, this **correct** rule for arrow:
```css
@media screen and (min-width: 1024px) {
  [data-tooltip].has-tooltip-bottom-desktop.has-tooltip-arrow:after { /* ... */ }
}
```

Gets overwritten with this **incorrect** (more specific) rule:
```css
[data-tooltip]:not(.is-disabled).has-tooltip-arrow.has-tooltip-arrow:after,
[data-tooltip]:not(.is-loading).has-tooltip-arrow.has-tooltip-arrow:after,
[data-tooltip]:not([disabled]).has-tooltip-arrow.has-tooltip-arrow:after { /* ... */ }
```
* result for touch breakpoint:
![Screenshot from 2020-05-10 11-04-29](https://user-images.githubusercontent.com/33978096/81495557-5324aa80-92b1-11ea-9098-7f27818764c9.png)

* result for desktop breakpoint:
![Screenshot from 2020-05-10 11-03-57](https://user-images.githubusercontent.com/33978096/81495559-561f9b00-92b1-11ea-9e67-944a01d5e24d.png)

---

And one request for bonus points. I would appreciate some classes for not displaying tooltip per different breakpoints. E.g.:
```css
.has-tooltip-hidden-#{$breakpoint} { /* ... */ }
```

Thanks

**Comment by CreativeBulma** [comment]
Hi @oliverfindl,

Thanks for reporting this bug. I'll work on it.
Good idea for
```sass
.has-tooltip-hidden-#{$breakpoint} { /* ... */ }
```

I'll try to integrate it too.
