### ISSUE TITLE
Feature request: Text align of tooltip

### ISSUE THREAD

**Issue by oliverfindl** [CreativeBulma/bulma-tooltip#6]
Hello @CreativeBulma,

it would be nice to have option to set different [text align](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align) of tooltip (globally and per different breakpoints) and its default sass variable. This will be useful for tooltips that contains new line characters or for `.has-tooltip-multiline` option.

Thanks

**Comment by CreativeBulma** [comment]
Hi @oliverfindl,

could be useful.

Any idea how to name those modifiers :
`has-tooltip-text-right` and `has-tooltip-text-centered` ?

**Comment by oliverfindl** [comment]
Hello @CreativeBulma,

Yes, basic ones:
* `.has-tooltip-text-centered`
* `.has-tooltip-text-right`
* `.has-tooltip-text-left` (for those, who will set different value than `left` via default sass variable)

And versions for different breakpoints. E.g.:
```css
.has-tooltip-text-centered.has-tooltip-text-left-touch
```

Thanks
