### ISSUE TITLE
Documentation missing code examples

### ISSUE THREAD

**Issue by Throwback74** [CreativeBulma/bulma-tooltip#7]
Hi! Not necessarily a code issue, but in your documentation you have "Preview" and "Code" tabs throughout the Get Started section, and you cannot switch over to the "Code" to see an example. 
Even when forcing it using the Inspector, it appears that there is no actual Code preview available there. I just wanted to bring this to your attention!

**Comment by CreativeBulma** [comment]
Hi,

can please try to refresh the documentation page ? it seems the JavaScript is not loaded on your side. it's working well on my side even on my mobile.

regards

**Comment by Throwback74** [comment]
![Screenshot_20200517-123923_Chrome](https://user-images.githubusercontent.com/36580003/82158282-b24b6780-983b-11ea-9394-bf9155b3af15.jpg)
![Screenshot_20200517-123918_Chrome](https://user-images.githubusercontent.com/36580003/82158283-b37c9480-983b-11ea-82ec-c37f861f04d5.jpg)

Same thing happens on my phone and on 3 different computers, I don't believe it's just me

**Comment by Throwback74** [comment]
Sorry, the above screenshots may not be clear, but I selected the "Code" tab in both of them, which you can see from the black underline, but it left the Preview active

**Comment by CreativeBulma** [comment]
I will investigate.

can you tell le if you're facing the same issue on other extensions documentations?

**Comment by qumeta** [comment]
same issues

**Comment by CreativeBulma** [comment]
can you tell me if you still hvaing the issue after clicking on "CTRL + MAJ + R" (on chrome or Firefox) ?

**Comment by qumeta** [comment]
> can you tell me if you still having the issue after pressing on "CTRL + MAJ + R" keys (on chrome or Firefox) ?
issue gone. 👍

**Comment by dyspop** [comment]
same issue. i've never visited the page before either.

**Comment by gbailey4** [comment]
Can't use any of the tabs as noted above as well. Tried on iOS Safari, macOS Safari, and macOS Chrome.

**Comment by yh54321** [comment]
Issue still exists...

**Comment by CreativeBulma** [comment]
this issue is driving me crazy.....don't understand why the JavaScript part not always loaded.....

**Comment by bassochette** [comment]
Same issue: Chrome on Ubuntu
When I ctrl+r : tabs are not working
When I ctrl+maj+r: tabs are working
