### ISSUE TITLE
New line / carriage return

### ISSUE THREAD

**Issue by helptiger** [CreativeBulma/bulma-tooltip#8]
Bug is back
https://github.com/Wikiki/bulma-tooltip/issues/34

change 
`white-space: pre`
to
`white-space: pre-line`

**Comment by helptiger** [comment]
several bugs, back to old bulma-tooltip

**Comment by CreativeBulma** [comment]
could you please elaborate so we will be able to fix them.

**Comment by helptiger** [comment]
Hello, I would like to do it, but unfortunately I do not have the time to do detailed research. I'm back to the versions of Wikiki that have worked very well so far.

**Comment by CreativeBulma** [comment]
we'll investigate. thanks for your feedback

**Comment by renejesusgv** [comment]
Still broken, I think you have a typo in the class "has-tooltipl-multiline". it should be "has-tooltip-multiline".
