### ISSUE TITLE
How do I import this package?

### ISSUE THREAD

**Issue by yh54321** [CreativeBulma/bulma-tooltip#9]
I have been using the 'bulma-tooltip' package in my React project and now want to upgrade to '@creativebulma/bulma-tooltip'.
I have been importing the packge (and all other css packages) with the following code:
`import 'bulma-tooltip/dist/css/bulma-tooltip.min.css';`

Now that I have installed the new tooltip package via npm, I have replaced that line with the following one:
`import '@creativebulma/bulma-tooltip/dist/css/bulma-tooltip.min.css';`

When launching the application, I get the following error:
"Module not found: Can't resolve '@creativebulma/bulma-tooltip/dist/css/bulma-tooltip.min.css'"

The 'Get Started' section of the documentation does not explain how to import the package.

Help with this matter will be appreciated

**Comment by yh54321** [comment]
Oh...the 'css' folder has been removed.
So it's: `import '@creativebulma/bulma-tooltip/dist/bulma-tooltip.min.css';`
Having importation instructions in the 'Get Started' can prevent such errors.

**Comment by oneblink-developers** [comment]
Is there a reason this is not in the documentation?
